### ISSUE TITLE
[EPIC] Yearly Program Plan - MPWG Repo Mktg Tasks

### ISSUE THREAD

**Issue by dalexandrov** [microprofile/microprofile-wg#174]
- [ ] [Grow MicroProfile community #151](https://github.com/microprofile/microprofile-wg/issues/151)
- [ ] [Define and track metrics on community outreach #150](https://github.com/microprofile/microprofile-wg/issues/150)
- [ ] [Continue to encourage participation across the wider community via mailing list, google group, and tweets. #149](https://github.com/microprofile/microprofile-wg/issues/149)
- [ ] [Empower the community with easily sharing their input via surveys and questionnaires #147](https://github.com/microprofile/microprofile-wg/issues/147)
- [ ] [Central location for promoting blogs, videos, products, etc that consume MicroProfile (highlight community content?) #146](https://github.com/microprofile/microprofile-wg/issues/146)
- [ ] [Individual component specification pages (see Jakarta specification pages for reference) #145](https://github.com/microprofile/microprofile-wg/issues/145)
- [ ] [Maintain and grow community participation in Marketing #142](https://github.com/microprofile/microprofile-wg/issues/142)
- [ ] [Strengthen the MicroProfile brand #138](https://github.com/microprofile/microprofile-wg/issues/138)
- [ ] [Create a MicroProfile Champions Program #132](https://github.com/microprofile/microprofile-wg/issues/132)
- [ ] [Create sitemap #70](https://github.com/microprofile/microprofile-wg/issues/70)

**Comment by aeiras** [comment]
<img width="760" alt="image" src="https://user-images.githubusercontent.com/10731224/189755061-0ac83c4a-9ead-4cdf-ad7b-febbb881725e.png">

@dalexandrov, 

Mitia, please be in the look out for the access invite from github. Do accept it asap when you see it. Do confirm access via this ticket.

**Comment by dalexandrov** [comment]
I have accepted

**Comment by jclingan** [comment]
Outdated. See the [2025 Program Plan](https://docs.google.com/presentation/d/1MajS5Y2OiQqF3g_pMWwM0P06Zsx9j4D9E1rnLwaj5mA/edit#slide=id.gbd5a24a629_1_0)
